AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'Rakefile'
    - 'bin/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'